service_name: travis-ci
repo_token: xvAsChqWor1OTi9FKIflX83viiT3WpIHb
coverageReporter: {
    dir: path.join(__dirname, 'coverage'),
    reporters: [
        {type: 'html'},
        {type: 'lcov', subdir: 'lcov'}  // lcov
    ]
}