language: node_js
node_js:
  - "7"
install:
|
  npm install -g npm@latest
  npm --version
  npm install -g cnpm --registry=https://registry.npm.taobao.org
  # npm install --registry http://registry.npmjs.org
  cnpm install
script:
  - npm test